Proyecto en clases/blog/apps/noticias/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('detalle/<int:pk>', views.DetalleNoticia, name='detalle'),
    path('addNoticia', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditarNoticia, name='edit_noticia'),
    path('comentario/add/<int:noticia_id>', views.AddComentario, name='add_comentario'),
    path('comentario/delete/<int:comentario_id>', views.BorrarComentario, name='delete_comentario'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto en clases/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    #parametro 1: es el texto de la url
    #parametro 2: la vista que se va a ejecutar
    #parametro 3: el nombre de la url
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto en clases/blog/apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    

class Noticia(models.Model):
    titulo = models.CharField(max_length=50) # = VARCHAR | max_length longitud max
    resumen = models.CharField(max_length=200, null=True)
    contenido = models.TextField()
    #imagen requiere la libreria pillow
    imagenes = models.ImageField(upload_to='noticias')
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    categoria_noticia = models.ForeignKey(Categoria, on_delete= models.SET_NULL, null=True) # models.CASCADE
    
    def default_autor():
        return Usuario.objects.get(is_superuser=True).pk
    
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, default=default_autor)
    

    def __str__(self):
        return self.titulo
    
class Comentario(models.Model):
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, related_name='comentarios')
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    usuario = models.CharField(max_length=50)

    def __str__(self):
        return self.contenido

Proyecto en clases/blog/apps/noticias/forms.py
from django import forms
from .models import Noticia, Comentario

class NoticiaForm(forms.ModelForm):

    class Meta:
        model = Noticia
        fields = [
            'titulo',
            'resumen',
            'contenido',
            'imagenes',
            'categoria_noticia',
        ]

class ComentarioForm(forms.ModelForm):
    
    class Meta:
        model = Comentario
        fields = [
            'contenido',
        ]
        exclude = ['usuario']
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)

        super(ComentarioForm, self).__init__(*args, **kwargs)
        if user:
            self.instance.usuario = user.username

Proyecto en clases/blog/apps/noticias/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Noticia, Categoria, Comentario
from .forms import NoticiaForm, ComentarioForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden

def ListarNoticias(request):
    contexto = {}
    id_categoria = request.GET.get("id", None)
    antiguedad = request.GET.get("antiguedad", None)
    orden = request.GET.get("orden", None)

    n = Noticia.objects.all()

    if id_categoria:
        n = n.filter(categoria_noticia=id_categoria)

    if antiguedad == "asc":
        n = n.order_by('fecha_publicacion')
    elif antiguedad == "desc":
        n = n.order_by('-fecha_publicacion')

    if orden == "asc":
        n = n.order_by('titulo')
    elif orden == "desc":
        n = n.order_by('-titulo')

    contexto = {
        'noticias': n,
        'categorias': Categoria.objects.all(),
    }

    return render(request, 'noticias/listar.html', contexto)


# DETALLE NOTICIA CON COMENTARIOS INCLUIDOS
def DetalleNoticia(request, pk):

    n = Noticia.objects.get(pk = pk) # SELECT * FROM NOTICIAS WHERE id = 1
    c = n.comentarios.all()

    #BORRAR NOTICIA
    if request.method == 'POST' and 'delete_noticia' in request.POST:
        n.delete()
        return redirect('noticias:listar')
    
    #COMENTARIO
    if request.method == 'POST' and 'add_comentario' in request.POST:
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.usuario = request.user
            form.save()
            return redirect('noticias:detalle', pk=pk)
    else:
        form = ComentarioForm()
    
    contexto = {
        'noticias': n,
        'comentarios': c,
        'form': form,
    }

    return render (request, 'noticias/detalle.html', contexto)


@login_required
def AddNoticia(request):
    if request.method == 'POST':
        form = NoticiaForm(request.POST or None, request.FILES) ##Request files es para las imagenes

        if form.is_valid():
            noticia = form.save(commit=False)
            noticia.autor = request.user
            form.save()
            return redirect('home')
    else:
        form = NoticiaForm()
    
    return render (request, 'noticias/addNoticia.html', {'form':form})


@login_required
def AddComentario(request, noticia_id):

    noticia = get_object_or_404(Noticia, id = noticia_id)   
    if request.method == 'POST':
        contenido = request.POST.get("contenido")
        usuario = request.user.username
        # creacion de comentario
        Comentario.objects.create(noticia = noticia, usuario = usuario, contenido = contenido)
    
    return redirect('noticias:detalle', pk = noticia_id)

@login_required
def BorrarComentario(request, comentario_id):

    comentario = get_object_or_404(Comentario, id = comentario_id)   
    if comentario.usuario == request.user.username:
        comentario.delete()
    
    return redirect('noticias:detalle', pk = comentario.noticia.pk)

@login_required
def EditarNoticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)

    # Solo el autor puede editar la noticia
    if noticia.autor != request.user:
        return HttpResponseForbidden("No tenes permiso para editar esta noticia.")

    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES, instance=noticia)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=pk)
    else:
        form = NoticiaForm(instance=noticia)

    context = {
        'form': form,
    }
    return render(request, 'noticias/editar.html', context)

Proyecto en clases/blog/templates/noticias/addNoticia.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido %}
    <h2>Crea una noticia</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}

Proyecto en clases/blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido %}
    <h2>Mi noticia detallada</h2>
    <div class="noti">
        <img src="{{noticias.imagenes.url}}" width="30%">
        <h3>{{noticias.titulo}}</h3>
        <p>{{noticias.contenido}}</p>
        <p>{{noticias.fecha_publicacion}}</p>
        <p>{{noticias.categoria_noticia}}</p>
        <p>Autor: {{noticias.autor}}</p>
        {% if user.is_authenticated and noticias.autor == user %}
        <a href="{% url 'noticias:edit_noticia' pk=noticias.pk %}">Editar</a>
            <form method="POST" action="{% url 'noticias:detalle' pk=noticias.pk %}">
                {% csrf_token %}
                <button type="submit" name="delete_noticia">BORRAR</button>
            </form>
        {% endif %}
    </div>
        <br>
        <h4>Comentarios</h4>
        {% for comentario in comentarios %}
            <p><strong>{{comentario.usuario}} - {{comentario.fecha_creacion}}</strong></p>
            <p>{{comentario.contenido}}</p>
            <form method="post" action="{% url 'noticias:delete_comentario' comentario.id %}">
                {% csrf_token %}
                {% if comentario.usuario == user.username %}
                    <button type="submit">Borrar</button>
                {% endif %}
            </form>
        <br>
        {% endfor %}
        {% if user.is_authenticated %} 
            <h4>Añadir comentarios</h4>
            <form method="post" action="{% url 'noticias:add_comentario' noticias.pk %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Enviar</button>
            </form>
        {% else %}
            <p>Debe iniciar sesión para dejar un comentario</p>
            <a href="{% url 'login' %}">INICIAR SESION</a>
        {% endif %}
        <a href="{% url 'noticias:listar' %}">VOLVER</a>
{% endblock contenido %}

Proyecto en clases/blog/templates/noticias/editar.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido %}
    <h2>Editar Noticia</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock contenido %}

Proyecto en clases/blog/templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido %}
    <h2>aca estan mis noticias !</h2>
    <form method="get" action="{% url 'noticias:listar'%}">
        <select name="id">
            <option value="">Todas</option>
            {% for cat in categorias %}
                <option value="{{cat.pk}}">{{cat.nombre}}</option>
            {% endfor %}
        </select>
        
        <select name="antiguedad">
            <option value="">Ordenar por Antigüedad</option>
            <option value="asc">Más antiguas primero</option>
            <option value="desc">Más recientes primero</option>
        </select>
        
        <select name="orden">
            <option value="">Ordenar alfabéticamente</option>
            <option value="asc">A - Z</option>
            <option value="desc">Z - A</option>
        </select>
        
        <input type="submit" value="Filtrar">
    </form>    
    {% for noticia in noticias %}
        <h3><a href="{% url 'noticias:detalle' noticia.pk %}">Titulo: {{noticia.titulo}}</a></h3>
        <img src="{{noticia.imagenes.url}}" width="10%">
        <br>
    {% endfor %}

{% endblock contenido %}