Proyecto en clases/blog/apps/noticias/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('detalle/<int:pk>', views.DetalleNoticia, name='detalle'),
    path('addNoticia', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditarNoticia, name='edit_noticia'),
    path('comentario/add/<int:noticia_id>', views.AddComentario, name='add_comentario'),
    path('comentario/delete/<int:comentario_id>', views.BorrarComentario, name='delete_comentario'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto en clases/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    #parametro 1: es el texto de la url
    #parametro 2: la vista que se va a ejecutar
    #parametro 3: el nombre de la url
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto en clases/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>Mi Blog {% block titulo %}{% endblock titulo %}</title>
</head>
<body class="contenedor">
    {% block contenido %}

    {% endblock contenido %}
    <a href="{% url 'nosotros' %}">IR A NOSOTROS</a>
    <a href="{% url 'home' %}">VOLVER AL INICIO</a>
    <a href="{% url 'noticias:listar' %}">NOTICIAS</a>
    {% if user.is_authenticated %}
        <strong>Hola {{ user.username }}</strong>
        <a href="{% url 'logout' %}">LOGOUT</a>
    {% else %}
        <a href="{% url 'login' %}">LOGIN</a>
        <a href="{% url 'registro' %}">REGISTRO</a>
    {% endif %}

</body>
</html>

Proyecto en clases/blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Home{% endblock titulo %}
{% block contenido %}
    <h2>hola mundo</h2>
{% endblock contenido %}

Proyecto en clases/blog/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Nosotros{% endblock titulo %}
{% block contenido %}
    <h2>soy de la comision 6</h2>
{% endblock contenido %}